# Generated by Django 6.0.7 on 2026-07-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "icv_taxonomy",
            "0001_squashed_0003_alter_term_vocabulary_alter_termassociation_term_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabulary",
            name="name",
            field=models.CharField(
                help_text="Human-readable name for the vocabulary. Unique globally, or within scope_field if set.",
                max_length=255,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="slug",
            field=models.SlugField(
                help_text="URL-safe identifier. Auto-generated from name if left blank (ICV_TAXONOMY_AUTO_SLUG=True).",
                max_length=255,
                verbose_name="slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="vocabulary",
            constraint=models.UniqueConstraint(fields=("name",), name="icv_taxonomy_vocabulary_name_uniq"),
        ),
        migrations.AddConstraint(
            model_name="vocabulary",
            constraint=models.UniqueConstraint(fields=("slug",), name="icv_taxonomy_vocabulary_slug_uniq"),
        ),
    ]
