# Generated by Django 6.1 on 2026-08-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icv_taxonomy", "0004_vocabulary_scope_field_uniqueness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="path",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Materialised path string (e.g. '0001/0002/0003'). Managed by icv-tree, do not edit directly.",
                max_length=255,
                verbose_name="path",
            ),
        ),
    ]
