# Generated by Django 5.2.17 on 2026-08-10 14:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSwapVocabulary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the vocabulary. Unique globally, or within scope_field if set.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier. Auto-generated from name if left blank (ICV_TAXONOMY_AUTO_SLUG=True).",
                        max_length=255,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of the vocabulary's purpose.",
                        verbose_name="description",
                    ),
                ),
                (
                    "vocabulary_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat"),
                            ("hierarchical", "Hierarchical"),
                            ("faceted", "Faceted"),
                        ],
                        default="flat",
                        help_text="Structural type of this vocabulary. Cannot be changed once terms exist (BR-TAX-002).",
                        max_length=20,
                        verbose_name="vocabulary type",
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=True,
                        help_text="If True, new terms may be added freely. If False, the vocabulary is closed to new terms (BR-TAX-003).",
                        verbose_name="is open",
                    ),
                ),
                (
                    "allow_multiple",
                    models.BooleanField(
                        default=True,
                        help_text="If True, objects may be tagged with multiple terms from this vocabulary.",
                        verbose_name="allow multiple",
                    ),
                ),
                (
                    "max_depth",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum allowed term depth (zero-based). Null means unlimited. Only meaningful for hierarchical vocabularies.",
                        null=True,
                        verbose_name="max depth",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary key/value metadata. Must be a JSON object.",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive vocabularies are hidden from default querysets.",
                        verbose_name="is active",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("name",), name="appswap_appswapvocabulary_name_uniq"),
                    models.UniqueConstraint(fields=("slug",), name="appswap_appswapvocabulary_slug_uniq"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AppSwapTerm",
            fields=[
                (
                    "path",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Materialised path string (e.g. '0001/0002/0003'). Managed by icv-tree, do not edit directly.",
                        max_length=255,
                        verbose_name="path",
                    ),
                ),
                (
                    "depth",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        editable=False,
                        help_text="Zero-based depth in the tree. Root nodes have depth=0.",
                        verbose_name="depth",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        editable=False,
                        help_text="Zero-based sibling ordering index within the parent. Used to compute path step values.",
                        verbose_name="order",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable term label.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier, unique within its vocabulary. Auto-generated from name if left blank (BR-TAX-007).",
                        max_length=255,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of this term.",
                        verbose_name="description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive terms are hidden from default querysets.",
                        verbose_name="is active",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary key/value metadata. Must be a JSON object.",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent node. Null for root nodes.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to=settings.ICV_TAXONOMY_TERM_MODEL,
                        verbose_name="parent",
                    ),
                ),
                (
                    "vocabulary",
                    models.ForeignKey(
                        help_text="The vocabulary this term belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.ICV_TAXONOMY_VOCABULARY_MODEL,
                        verbose_name="vocabulary",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
                "abstract": False,
                "unique_together": {("vocabulary", "path"), ("vocabulary", "slug")},
            },
        ),
    ]
